# Packet Config
# Any required values not specified will have a default config

# TCP Config
TCP:
  dport: 123
  sport: 5050

# UDP Config
#UDP:
# dport: 53

# IP Config
IP:
  dst: 25.25.25.25

# Ether Config
Ether:
  dst: aa:bb:cc:dd:ee:ff

# Settings
Settings:
  mode: loop
  #iface_index: 0
  interval: 3
